### ISSUE TITLE
Clients not coming up on home

### ISSUE THREAD

**Issue by breixopd** [FarisCode511/BlackNET#8] opened 2020-11-11 19:28 UTC
If i look at logs the clients are connecting but theyre not appearing in the dashboard, i have blacknet running on 000webhost and i ran the client on my own PC to test.
![image](https://user-images.githubusercontent.com/32527555/98855483-fd91ac00-2453-11eb-820b-847884041386.png)
![image](https://user-images.githubusercontent.com/32527555/98855513-07b3aa80-2454-11eb-922d-08222e7a6509.png)

The clients arent being added to the DB but the DB is working fine since the users are working

**Comment by breixopd** [comment] 2020-11-12 17:11
I enabled debug mode and compiled another client and the logs.txt file is empty

**Comment by FarisCode511** [comment] 2020-11-12 17:46
Did you enable any builder features like "Elevate UAC" so I can debug them properly

**Comment by FarisCode511** [comment] 2020-11-12 18:01
> I enabled debug mode and compiled another client and the logs.txt file is empty

Did you enable any builder features like "Elevate UAC" or any other feature so I can debug them properly? 

and check a folder called error_logs if it has any .log files please attach them

**Comment by breixopd** [comment] 2020-11-12 21:33
Ill try with Elevate UAC now

**Comment by breixopd** [comment] 2020-11-12 22:11
Done, nothing in the error_logs folder and the logs.txt file in the builder has nothing either but it came up correctly in the logs in the actual panel
![image](https://user-images.githubusercontent.com/32527555/99002238-05c11880-2534-11eb-8c35-ff8aa420edcf.png)

**Comment by nicken648** [comment] 2020-11-14 14:54
The same problem (

**Comment by nicken648** [comment] 2020-11-14 16:27
I turned on the debugmod and it says in the logs:"The remote server returned an error: (500) Internal server error."

**Comment by breixopd** [comment] 2020-11-14 16:30
It doesnt say anything for me

**Comment by FarisCode511** [comment] 2020-11-15 07:10
I am looking into it the issue is 000webhost work just fine, connection success and I can send and receive commands through 000webhost without issues but I will look into it might be something in the installation process.

**Comment by ibzann** [comment] 2020-11-24 18:10
Same thing here, I'm using 000webhost and the clients do not show up. But the logs say the client is connected.
![image](https://user-images.githubusercontent.com/55029662/100134504-f011f400-2e4d-11eb-801e-f1ed3f01b184.png)
![image](https://user-images.githubusercontent.com/55029662/100134569-0750e180-2e4e-11eb-8dfa-04d2086e8af5.png)

**Comment by FarisCode511** [comment] 2020-11-24 19:14
> Same thing here, I'm using 000webhost and the clients do not show up. But the logs say the client is connected.
> ![image](https://user-images.githubusercontent.com/55029662/100134504-f011f400-2e4d-11eb-801e-f1ed3f01b184.png)
> ![image](https://user-images.githubusercontent.com/55029662/100134569-0750e180-2e4e-11eb-8dfa-04d2086e8af5.png)

The issue is already been addressed and will be fixed in the next version.

**Closed** 2020-11-26 13:05 UTC
